name: Train Model
on:
  workflow_dispatch:
    inputs:
      model-name:
        required: true
        description: The name of the Hugging Face repository to save the model (e.g., `Roshmikax/PonySDXL_Navodi`).
      trigger-word:
        required: true
        description: The trigger word for the model.
        default: Navodix
      max-train-steps:
        required: true
        description: The total number of training steps.
        default: '2000'
jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
          pip install transformers diffusers accelerate safetensors pillow requests

      - name: Run Training Script
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          python train_lora.py \
            --data_url "https://huggingface.co/Roshmikax/sdxlnngi/resolve/main/navodi.zip" \
            --checkpoint_url "https://civitai.com/api/download/models/290640?type=Model&format=SafeTensor&size=pruned&fp=fp16" \
            --output_dir "./output" \
            --trigger_word "${{ github.event.inputs.trigger-word }}" \
            --hf_token "$HUGGINGFACE_TOKEN" \
            --config "config.json"

      - name: List Dataset Contents
        run: |
          echo "Listing contents of ./dataset:"
          ls -R ./dataset

      - name: Upload Model to Hugging Face
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          huggingface-cli login --token "$HUGGINGFACE_TOKEN"
          cd output
          git init
          git remote add origin "https://huggingface.co/${{ github.event.inputs.model-name }}"
          git add .
          git commit -m "Add trained model"
          git push origin main --force
