name: Train LoRA Model

on:
  workflow_dispatch:
    inputs:
      model-name:
        required: true
        description: The name of the Replicate model to publish, in the format `your-replicate-username/desired-model-name`.
      prompt-identifier:
        required: true
        description: A custom string to trigger the style in prompts (e.g., "Navodix").
      max-train-steps:
        required: true
        description: Total number of training steps to perform.
        type: number
        default: 2000

env:
  REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
  HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}

jobs:
  train-lora:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch transformers diffusers datasets accelerate loralib cog

      - name: Download Base Checkpoint
        run: |
          wget -O base_model.safetensors https://civitai.com/api/download/models/290640?type=Model&format=SafeTensor&size=pruned&fp=fp16&token=075a4e5a368529bba1bd492fd2443386

      - name: Download Training Dataset
        run: |
          wget -O navodi.zip https://huggingface.co/Roshmikax/sdxlnngi/resolve/main/navodi.zip
          unzip navodi.zip -d dataset

      - name: Setup Hugging Face CLI
        run: |
          huggingface-cli login --token ${{ secrets.HUGGINGFACE_TOKEN }}

      - name: Start LoRA Training
        run: |
          cog run python train_lora.py \
            --model_path base_model.safetensors \
            --dataset_path ./dataset \
            --save_dir ./output \
            --resolution 512 \
            --train_batch_size 4 \
            --epochs 10 \
            --max_train_steps ${{ inputs.max-train-steps }} \
            --shuffle_tags True \
            --keep_tokens True \
            --clip_skip 2 \
            --flip_aug True \
            --unet_lr 0.0001 \
            --text_encoder_lr 0.00005 \
            --lr_scheduler cosine \
            --lr_scheduler_cycles 2 \
            --min_snr_gamma 5.0 \
            --network_dim 128 \
            --network_alpha 128 \
            --noise_offset 0.02 \
            --optimizer "Prodigy" \
            --optimizer_args "weight_decay=0.01, adam_epsilon=1e-8"

      - name: Save Trained Model to Hugging Face
        run: |
          huggingface-cli upload ./output --repo Roshmikax/PonySDXL_Navodi --token ${{ secrets.HUGGINGFACE_TOKEN }}

      - name: Link to Model on Replicate
        run: |
          curl -s -X POST \
            -H "Authorization: Token ${{ secrets.REPLICATE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "input": {
                "instance_prompt": "a photo of ${{ inputs.prompt-identifier }} person",
                "class_prompt": "a photo of a person",
                "instance_data": "${{ steps.upload-training-data.outputs.INSTANCE_DATA_URL }}",
                "max_train_steps": ${{ inputs.max-train-steps }}
              },
              "model": "${{ inputs.model-name }}",
              "trainer_version": "cd3f925f7ab21afaef7d45224790eedbb837eeac40d22e8fefe015489ab644aa"
            }' \
          https://dreambooth-api-experimental.replicate.com/v1/trainings
